menu:

  koalamon_project_admin:

    tools_sub_heart_default:
      parent: tools_main
      label: Heart Beat
      options:
        route: koalamon_heartbeat_homepage
        routeParameters:
          project: @route