services:

    koalamon.heartbeat.adminMenu:
        class: Koalamon\HeartbeatBundle\EventListener\PluginListener
        arguments: [ @service_container ]
        tags:
            - { name: 'kernel.event_listener', event: 'koalamon.plugin.admin.menu.init', method: onKoalamonPluginAdminMenuInit }