koalamon_incident_dashboard:
    resource: "@KoalamonIncidentDashboardBundle/Resources/config/routing.yml"
    prefix:   /

koalamon_gecko_board:
    resource: "@KoalamonGeckoBoardBundle/Resources/config/routing.yml"
    prefix:   /

koalamon_plugin:
    resource: "@KoalamonPluginBundle/Resources/config/routing.yml"
    prefix:   /

koalamon_integration:
    resource: "@KoalamonIntegrationBundle/Resources/config/routing.yml"
    prefix:   /

koalamon_information:
    resource: "@KoalamonInformationBundle/Resources/config/routing.yml"
    prefix:   /

koalamon_notification:
    resource: "@KoalamonNotificationBundle/Resources/config/routing.yml"
    prefix:   /

koalamon_default:
    resource: "@KoalamonDefaultBundle/Resources/config/routing.yml"
    prefix:   /

koalamon_rest:
    resource: "@KoalamonRestBundle/Resources/config/routing.yml"
    prefix:   /

koalamon_stat:
    resource: "@KoalamonStatBundle/Resources/config/routing.yml"
    prefix:   /

koalamon_webhook:
    resource: "@KoalamonWebhookBundle/Resources/config/routing.yml"
    prefix:   /
