menu:

  koalamon_project_admin:

    systems_sub_health_status:
      parent: systems_main
      label: Health Status
      options:
        route: koalamon_health_status_homepage
        routeParameters:
          project: @route