services:

    koalamon.healthstatus.eventCreationListener:
        class: Koalamon\HealthStatusBundle\EventListener\EventListener
        arguments: [ @service_container ]
        tags:
            - { name: 'kernel.event_listener', event: 'koalamon.event.create', method: onEventCreate }