services:

    koalamonintegration.koalaping.init:
        class: Koalamon\Bundle\Integration\KoalaPingBundle\EventListener\IntegrationListener
        arguments: [ @service_container ]
        tags:
            - { name: 'kernel.event_listener', event: 'koalamon.integration.init', method: onInit }