menu:

  koalamon_project_main:

    status:
      label: Status
      options:
        route: bauer_incident_dashboard_core_homepage
        routeParameters:
          project: @route

        attributes:
          class: status_count_label

    twentyfour:
      label: History
      options:
        route: bauer_incident_dashboard_core_past
        routeParameters:
           intervalInHours: 24
           project: @route

    systems:
      label: Systems
      options:
        route: bauer_incident_dashboard_core_systems
        routeParameters:
          project: @route

    tools:
      label: Tools
      options:
        route: bauer_incident_dashboard_core_tools
        routeParameters:
          project: @route

  koalamon_project_admin:

    project_main:
      label: Project
      options:
        route: koalamon_default_project_admin
        routeParameters:
          project: @route

    collaborators_main:
      label: Collaborators
      options:
        route: koalamon_default_user_admin
        routeParameters:
          project: @route

    systems_main:
      label: Systems
      options:
        route: koalamon_default_system_admin
        routeParameters:
          project: @route

    systems_sub_default:
      parent: systems_main
      label: Default
      options:
        route: koalamon_default_system_admin
        routeParameters:
          project: @route

    tools_main:
      label: Tools
      options:
        route: koalamon_default_tool_admin
        routeParameters:
          project: @route

    tools_sub_default:
      parent: tools_main
      label: Tools
      options:
        route: koalamon_default_tool_admin
        routeParameters:
         project: @route

    translation_main:
      label: Translations
      options:
        route: koalamon_default_admin_translation_home
        routeParameters:
          project: @route
