menu:

  koalamon_project_main:

    status:
      name: Status
      route: bauer_incident_dashboard_core_homepage
      projectAware: true
      attributes:
        class: status_count_label

    twentyfour:
      name: History
      route: bauer_incident_dashboard_core_past
      routeParameters:
        intervalInHours: 24
      projectAware: true

    systems:
      name: Systems
      route: bauer_incident_dashboard_core_systems
      projectAware: true

    tools:
      name: Tools
      route: bauer_incident_dashboard_core_tools
      projectAware: true


  koalamon_project_admin:

    project_main:
      name: Project
      route: koalamon_default_project_admin
      projectAware: true

    collaborators_main:
      name: Collaborators
      route: koalamon_default_user_admin
      projectAware: true

    systems_main:
      name: Systems
      route: koalamon_default_system_admin
      projectAware: true

    systems_sub_default:
      parent: systems_main
      name: Default
      route: koalamon_default_system_admin
      projectAware: true

    tools_main:
      name: Tools
      route: koalamon_default_tool_admin
      projectAware: true

    tools_sub_default:
      parent: tools_main
      name: Tools
      route: koalamon_default_tool_admin
      projectAware: true

    translation_main:
      name: Translations
      route: koalamon_default_admin_translation_home
      projectAware: true